version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "webapp-container"
          ContainerPort: 8080
Hooks:
  - BeforeInstall: "BeforeInstallHook"
  - AfterInstall: "AfterInstallHook"
  - AfterAllowTestTraffic: "AfterAllowTestTrafficHook"
  - BeforeAllowTraffic: "BeforeAllowTrafficHook"
  - AfterAllowTraffic: "AfterAllowTrafficHook"