name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this if needed

env:
  AWS_REGION: us-east-1  # Change to your region
  ECR_REPOSITORY: week5-lab-ecr-nicholas  # Change to your ECR repo name
  INFRASTRUCTURE_REPO: OppongNicholas303/S3-Image-Application-Infrastructure
  STACK_NAME: S3AppStack
  ECS_CLUSTER: S3AppCluster
  ECS_SERVICE: S3AppService

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.INFRASTRUCTURE_REPO }}
          path: infrastructure

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/infastructure.yaml \
            --stack-name $STACK_NAME \
            --parameter-overrides ImageUri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest \
            --capabilities CAPABILITY_IAM

      - name: Trigger Blue/Green Deployment in ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment
